### ISSUE TITLE
Elaborate a way to calculate and present (show) Sizes on Ratel. | used space

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#10]
![image](https://user-images.githubusercontent.com/6570955/42126939-4dc14b38-7c66-11e8-92c7-652a1eb56efc.png)

I was talking to Karandeep Singh in Slack, and I noticed there's this demand. He even talked to others and saw other people too.

Hence I remembered that tools like phpmyadmin have (as an example of an HTML viewer) a field that displays the size of the entire DB and tables. It would be interesting to have a set of space usage statistics. And each predicate also have its evaluation of space usage separate.

PS. Also taking into consideration Shards (if possible)

I know this would be technically complex to put in Ratel, but it's interesting.

**Comment by paulftw** [comment]
Closing as this is tracked in different jira cards now
