### ISSUE TITLE
Dgraph v1.1.0: Visualization does not show one-to-one edges

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#106]
Dgraph v1.1.0 supports specifying one-to-one edges using the `uid` schema type. e.g.,

```
friend: uid .
```

This enforces the predicate to only have a single outgoing edge per node. e.g., instead of having a list of friends, each person would only be allowed to have one friend.

https://github.com/dgraph-io/dgraph/pull/2921 changed the query response for one-to-one uid edges to output as a single JSON map instead of an array. This breaks the graph visualization for one-to-one edges.

### Steps to reproduce

Set schema for a single uid edge:
```
friend: uid .
```

Set mutation:
```
{
  "set": [
    {
      "name": "Alice",
      "friend": {
        "name": "Bob"
      }
    }
  ]
}
```

Run query:

```
{
  q(func: has(name)) {
    name
    friend {
      name
    }
  }
}
```

Query response (does not have JSON array for `"friend"`):

```json
{
  "data": {
    "name": "Alice",
    "friend": {
      "name": "Bob"
    }
  }
}
```

Query visualization in Ratel:

![image](https://user-images.githubusercontent.com/2251820/63377874-c5c9b080-c345-11e9-8f3f-252aedcacb0f.png)

### Expected results

The visualization should show the `friend` edge. This works for `[uid]` edges, as shown below.

#### Steps to reproduce expected results

Set schema for list `[uid]` edge:
```
friend: [uid] .
```

Set mutation:
```
{
  "set": [
    {
      "name": "Alice",
      "friend": {
        "name": "Bob"
      }
    }
  ]
}
```

Run query:

```
{
  q(func: has(name)) {
    name
    friend {
      name
    }
  }
}
```

Query response (JSON array for `"friend"`):

```json
{
  "data": {
    "name": "Alice",
    "friend": [
      {
        "name": "Bob"
      }
    ]
  }
}
```

![image](https://user-images.githubusercontent.com/2251820/63377922-e98cf680-c345-11e9-86e1-8295e9bec1f8.png)

**Comment by paulftw** [comment]
This is happening because Ratel expects edges to be represented as arrays.
In 0.16 response would probably be `friend: [{...bob's fields...}]` but in 1.1 it is `friend: {...bob's fields...}`

GraphParser needs to be updated to support this type of data.

**Comment by danielmai** [comment]
Looks like this issue was fixed in https://github.com/dgraph-io/ratel/commit/7559df47ef37eb535b33ca0ca08de739a4083bd1.

I see the fix in the ?latest distribution, but not the ?dev distribution.

![2019-09-03-114655_1717x1413_scrot](https://user-images.githubusercontent.com/2251820/64200052-8c626c00-ce40-11e9-9290-8c030452d5b7.png)

**Comment by paulftw** [comment]
yes, dev is most likely missing it because it's not built from master (for a short while).
I'll close this issue, dev will get updated next time we ship it.
