### ISSUE TITLE
Type system editor: Cannot set type name with special characters

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#116]
![image](https://user-images.githubusercontent.com/2251820/64394663-0e52c080-d00c-11e9-9e43-434c17f357d4.png)

Steps to reproduce:

- Go to the Schema tab and select Types
- Click the Add Type
- Set the Type Name as `née`
- Click Create Type

**Comment by paulftw** [comment]
https://github.com/dgraph-io/ratel/pull/122
