### ISSUE TITLE
Type system editor: uid field types cannot be references to other type names 

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#117]
Steps to reproduce

1. In Bulk Edit (or outside of Ratel), create the following schema with a type field that refers to a different type

```
refersTo: [uid] .
type TypeA {
  refersTo: [TypeB]
}
```

The type definition shows that refersTo is of type [TypeB]

![image](https://user-images.githubusercontent.com/2251820/64396823-cc2d7d00-d013-11e9-9f65-a01504ad78aa.png)

When clicking on Edit Type, the predicate name along with its actual type is shown

![image](https://user-images.githubusercontent.com/2251820/64396866-f1ba8680-d013-11e9-92fd-6a5a2337eadf.png)

After clicking Save, the field type turns into [uid]

![image](https://user-images.githubusercontent.com/2251820/64396880-0139cf80-d014-11e9-8ea8-e5f20f8ee45e.png)

Expected result:

The type definition should retain the information that refersTo references TypeB nodes.

**Comment by danielmai** [comment]
A related issue is, as implied by Step 1, we can't create types in the UI that refer to other types by name.

**Comment by paulftw** [comment]
https://github.com/dgraph-io/ratel/pull/123

**Comment by paulftw** [comment]
Fixed, and type system is going to be typeless soon, so probably not needed anymore
