### ISSUE TITLE
Type system: Graph visualization should connect known edges together

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#118]
In Dgraph v1.1 when running schema query (`schema {}`), Ratel shows a graph visualization of the types. This looks great. It would be nice to have the types with fields to other named types visualized as an edge between those two types. Today, every type is its own node, and all the outgoing edges are the fields of that type. There are no connections between types.

**Comment by paulftw** [comment]
I like the idea

**Comment by paulftw** [comment]
Just tried on a local instance, it actually works for types created from UI.
Is it different on your system, @danielmai ?

<img width="1219" alt="Screen Shot 2019-09-13 at 3 51 34 PM" src="https://user-images.githubusercontent.com/769142/64863839-702fad80-d63e-11e9-9272-e8e8e114b9be.png">

**Comment by danielmai** [comment]
The pink nodes are the edge names, right? They're not other node types.

**Comment by danielmai** [comment]
Here's an example to show what I mean by "connect known edges together" across types:

Add these types to a new Dgraph cluster:

```
type TypeA {
	name: string
	connectedTo: [TypeB]
}
type TypeB {
	name: string
}
```

The `schema {}` visualization looks like this:

![image](https://user-images.githubusercontent.com/2251820/64864881-e60b2900-d5ec-11e9-9aca-ec45800d4de6.png)

The green nodes can be via the "connectedTo" edge, as mentioned in the type definition of TypeA.
