### ISSUE TITLE
Run upserts

### ISSUE THREAD

**Issue by pepoospina** [dgraph-io/ratel#119]
How can run an upsert from Ratel?
```
{
  upsert {
    query {
      v as var(func: eq(email, "user@company1.io"))
    }

    mutation {
      set {
        uid(v) <name> "first last" .
        uid(v) <email> "user@company1.io" .
      }
    }
  }
}
```

**Comment by paulftw** [comment]
@mangalaman93 how is it supposed to work via HTTP?
Currently for the upsert above Ratel sends `/mutate` with content-type `application/rdf` but server returns `Error while lexing <query above> at line 2 column 10: Invalid character '{' inside mutation text`

**Comment by mangalaman93** [comment]
The outermost braces are causing the issuex just remove them. 

```
upsert {
    query {
      v as var(func: eq(email, "user@company1.io"))
    }

    mutation {
      set {
        uid(v) <name> "first last" .
        uid(v) <email> "user@company1.io" .
      }
    }
  }
```

**Comment by paulftw** [comment]
Seems like removing brackets will solve the issue. 
Closing the github bug for now.

@pepoospina please feel free to reopen if you still have problems sending an upsert mutation via Ratel

**Comment by onkarbanerjee** [comment]
Using uid(v) as the object in the mutation doesn't work though.
