### ISSUE TITLE
type system can't add predicate with ":"

### ISSUE THREAD

**Issue by zhuyaoyhj** [dgraph-io/ratel#121]
I want to create type system with ratel, but the following situation occurs。Type system Test can't add predicate with ":".
![image](https://user-images.githubusercontent.com/35676978/65019843-9a46df80-d95e-11e9-8753-2eb840979fcf.png)

**Comment by manishrjain** [comment]
Try putting brackets around it `<>`.

**Comment by paulftw** [comment]
Same as i18n characters `:` would violate graphql spec, but a PR is under review:
https://github.com/dgraph-io/ratel/pull/122

**Comment by campoy** [comment]
This should be supported by Ratel, yeah.

Thanks for the support @paulftw
