### ISSUE TITLE
Customize Ratel serving address

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#132]
By default Ratel serves the UI over `:::8000` (all addresses). The `-port` flag exists today to customize the port (default: 8000). There should also be a flag to configure the address. For example, it can be useful to restrict the Ratel web server to only allow access via the server itself on localhost.

**Comment by paulftw** [comment]
Bad actors can run Ratel locally to bypass this restriction, so it doesn't introduce any extra security.
What are other reasons to add this feature?

**Comment by paulftw** [comment]
IIRC Ahmed already merged this in. Please reopen if more configuration is still needed
