### ISSUE TITLE
ACL incorrectly creates ACL users

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#136]
Same as #135, but for users.

Steps to reproduce:

1. Run Dgraph cluster with ACLs enabled
2. Login as groot
3. Add a ACL user called "aUser"
4. Query for the group with the CLI tool:

```
$ dgraph acl info -u aUser
[Decoder]: Using assembly version of decoder

Running transaction with dgraph endpoint: 127.0.0.1:9080
Current password for groot:
Login successful.
Unable to show info: The user "aUser" does not exist.
```

Although Ratel says there's a user, it's not detected via the CLI tool.

**Comment by paulftw** [comment]
Fixed in master, new build is out.
Please re-open if you see this problem again
