### ISSUE TITLE
Bug in Add Predicate panel

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#139]
![Captura de Tela 2019-10-18 às 13 48 54](https://user-images.githubusercontent.com/6570955/67112625-0c088800-f1ae-11e9-8d3e-fb1c9d4aa220.png)

```
Could not alter predicate: line 1 column 14: Indexing not allowed on predicate movie of type uid
```
This is in `?latest` an `?dev` And the `@count` for` uid` was removed.

**Comment by paulftw** [comment]
Will add this issue to the next sprint
