### ISSUE TITLE
Add way to drop data.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#159]
Today in Ratel there's a "DROP ALL" button to drop all the data and schema in Dgraph.

Dgraph also has a way to drop just the data (not the schema). This should be doable in the Ratel UI.

Here's how [drop data](https://docs.dgraph.io/clients/#alter-the-database-1) would be done via curl:

```
curl -X POST localhost:8080/alter -d '{"drop_op": "DATA"}'
```

**Comment by paulftw** [comment]
Fixed in 60d5c
