### ISSUE TITLE
Error occurs when password is less than 6 characters

### ISSUE THREAD

**Issue by animesh2049** [dgraph-io/ratel#163]
When I try to create a user having password of less than 6 character, ratel gets error internally.
![Screenshot from 2020-02-11 16-46-41](https://user-images.githubusercontent.com/15055935/74232674-4bc02600-4cef-11ea-8601-89023fdc9212.png)

**Comment by sleto-it** [comment]
I agree the error is not intuitive
When trying from the command line the error message is more clear:

```
unable to create user: rpc error: code = Unknown desc = Password too short, i.e. should have at least 6 chars
```
