### ISSUE TITLE
Refactor Frame UI: Make visual / raw result consistent

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/ratel#170]
Mutation result has following tabs: Message, JSON, Request, Geo (should be removed separately)
Query result has following tabs: Graph, JSON, Request, Geo

Message and Graph serve almost same purpose: visual representation of the JSON response.
Graph, Geo (and upcoming timeline) are just submodes of this visual representation, specific to the type response data.

It is thus logical to unify naming and behavior of the result tabs 
1) visually: consistent naming, moving different visualizations as sub controls of the visual tab
2) in the code: code that handles frame results, query debug data, active tab is far from clean, adding a logical abstraction to guide how data is stored in redux and mapped to components will help clean it up

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8033). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
