### ISSUE TITLE
Please, remove the "Delete" button if the node has no dgraph type.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#172]
Users can be confused and frustrated when trying to delete a node via the UI. Because when a node does not have the predicate "dgraph.type", it is not possible to delete it. It is necessary to add a well-defined Type to be able to do this. And Dgraph can't do it automatically.

See this user experience here https://discuss.dgraph.io/t/ratel-delete-node-function-query-seems-wrong/6071/4

If this is already implemented, please just close this.

**Comment by praneelrathore** [comment]
Thanks Michel.
