### ISSUE TITLE
Show Dgraph version in Ratel

### ISSUE THREAD

**Issue by sleto-it** [dgraph-io/ratel#174]
It would be useful if we show, in Ratel, the Dgraph version
We have already this info internally, we just need to show it

This will help us a lot especially when one is connected to different versions of Dgraph, on different browser tabs, to identify the version we are working on 

A good position could be in the left page, after the 'help' button

Thanks,

**Comment by paulftw** [comment]
Added as part of https://github.com/dgraph-io/ratel/commit/93f42173ac315455bda11d07095daa68c5206ab6
