### ISSUE TITLE
we are getting connection issue with new New Connection UI

### ISSUE THREAD

**Issue by anilpaladuguvoltuswave** [dgraph-io/ratel#184]
we can't mutate with new ratel ui and connection ui also having issues :

1. connecting to server but it was showing connection issue

**Comment by paulftw** [comment]
do you have ACL enabled?
Are there any errors in the Chrome Dev console?
What Dgraph version are you connecting to?

**Comment by paulftw** [comment]
Closing as duplicate of #183 
Please provide any extra information either here or in the issue #183

**Comment by paulftw** [comment]
Alternatively you can reach out to our support team at https://slack.dgraph.io/ or https://discuss.dgraph.io/
