### ISSUE TITLE
Skewed ratel tabs on safari browser

### ISSUE THREAD

**Issue by praneelrathore** [dgraph-io/ratel#194]
The ratel tabs (json, graph, query, geo) doesn't look proper in safari browser as can be seen in the following image -

![image](https://user-images.githubusercontent.com/7555160/80354232-152c8d00-8894-11ea-98a8-aa8aeec6cec4.png)

Not a big issue though, just flagging it.

**Comment by paulftw** [comment]
That's weird. Looks fine to me in Safari 13.1

However, if I cmd-minus a couple of times I get very similar oversized icons.
@praneelrathore have you tried Cmd+Zero? Maybe the tab accidentally got zoomed out?

**Comment by paulftw** [comment]
I'll close the issue for now. Please re-open if it's not a zoom issue
