### ISSUE TITLE
[Feature request] Support bookmarking queries.

### ISSUE THREAD

**Issue by anukul-mohil** [dgraph-io/ratel#195]
I find myself going back and forth in ratel history to find queries I've made, or copy/paste them to some external file.
Would be really nice if you guys can support bookmarking queries in ratel, would be great if we can share these like [Postman collections](https://learning.postman.com/docs/postman/collections/intro-to-collections/) too.

**Comment by MichelDiz** [comment]
This seems a reasonable request. But isn't https://github.com/dgraph-io/ratel/issues/171 the same request?

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8686). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
