### ISSUE TITLE
Bulk Edit button looks like just text

### ISSUE THREAD

**Issue by darkn3rd** [dgraph-io/ratel#197]
The bulk edit button is black text on white background, while other clickable links that are used as buttons have blue background with rounded corners, so they look like clickable buttons.

### Dgraph Version

`latest`

### Tech Specs

* Ubuntu 18.04
* Chromium 79.0.3945.130

### Steps 

1. Ratel
2. Schema
3. Observe Bulk Edit

### Expected

Blue Background like other buttons (clickable text)

### Actual

Black Text on White background

**Comment by paulftw** [comment]
This is by design: "Refresh Schema" and "Bulk Edit" are considered secondary operations, only needed when UI is not enough, so they've been made less prominent in the UI.

Will add hover effects to make it clearer those are clickable
