### ISSUE TITLE
Dgraph v1.0.x: Server status shows connection error but queries/mutations/schema requests work

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#200]
When connecting to Dgraph v1.0.x, Ratel shows that the server is not connected. The status says there's a connection issue, but requests for queries, mutations, and schema all work.

![ratel-connection](https://user-images.githubusercontent.com/2251820/80736485-10035400-8ac7-11ea-905d-28369a78ae8d.png)

Steps to reproduce

1. Run Dgraph cluster running v1.0.x
2. Go to Ratel latest and connect to the Dgraph cluster.

**Comment by paulftw** [comment]
Fixed in 6de186f
