### ISSUE TITLE
Dgraph v1.0.x: Mutations are not committed

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#201]
Mutations sent when connecting to a Dgraph v1.0.x cluster are not committed.

Steps to reproduce:

1. Run a Dgraph cluster running v1.0.x.
2. Run a mutation in the Mutate tab. There's no "commit" message in the mutation response.

**Comment by danielmai** [comment]
The network request for the mutation ran `/mutate?commitNow=true`. In Dgraph v1.0.x, CommitNow should be set with the header `X-Dgraph-CommitNow: true`.

**Comment by paulftw** [comment]
Fixed in 30412faf2ca8
