### ISSUE TITLE
./scripts/build.prod.sh fails build process

### ISSUE THREAD

**Issue by smeadows-abb** [dgraph-io/ratel#203]
go install fails and ./scripts/build.prod.sh fails during build process.

**GO INSTALL** 
# github.com/dgraph-io/ratel/server
server/server.go:99:13: undefined: Asset
server/server.go:107:13: undefined: Asset
server/server.go:112:15: undefined: AssetInfo
server/server.go:154:14: undefined: Asset
server/server.go:160:16: undefined: AssetInfo

**build.prod.sh**
loadDep:color-convert → a ▐ ╢████████████████████████████████████████████████░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░░╟
npm ERR! Linux 5.3.0-51-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install"
npm ERR! node v8.10.0
npm ERR! npm  v3.5.2
npm ERR! code EMISSINGARG

npm ERR! typeerror Error: Missing required argument #1
npm ERR! typeerror     at andLogAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:31:3)
npm ERR! typeerror     at fetchPackageMetadata (/usr/share/npm/lib/fetch-package-metadata.js:51:22)
npm ERR! typeerror     at resolveWithNewModule (/usr/share/npm/lib/install/deps.js:456:12)
npm ERR! typeerror     at /usr/share/npm/lib/install/deps.js:457:7
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror     at /usr/share/npm/lib/fetch-package-metadata.js:37:12
npm ERR! typeerror     at addRequestedAndFinish (/usr/share/npm/lib/fetch-package-metadata.js:82:5)
npm ERR! typeerror     at returnAndAddMetadata (/usr/share/npm/lib/fetch-package-metadata.js:117:7)
npm ERR! typeerror     at pickVersionFromRegistryDocument (/usr/share/npm/lib/fetch-package-metadata.js:134:20)
npm ERR! typeerror     at /usr/share/npm/node_modules/iferr/index.js:13:50
npm ERR! typeerror This is an error with npm itself. Please report this error at:
npm ERR! typeerror     <http://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /home/smeadows/go/src/github.com/dgraph-io/ratel/client/npm-debug.log
smeadows@thinkpad:~/go/src/github.com/dgraph-io/ratel$

**Comment by paulftw** [comment]
Has it printed anything about `Could not find go-bindata`?

**Comment by paulftw** [comment]
What is the exact command you are trying to run?
Building and running Ratel from source is covered in the [INSTRUCTIONS.md](https://github.com/dgraph-io/ratel/blob/master/INSTRUCTIONS.md)

**Comment by paulftw** [comment]
I've updated the INSTRUCTIONS.md and improved the build.prod.sh to better handle missing `go-bindata`
Verified the updated build on a clean ec2linux machine.
Some errors are still being printed but current logging and documentation are hopefully good enough.

Please re-open this issue if there are still unexpected errors during the build.
