### ISSUE TITLE
Support running indexing in background.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#207]
As of Dgraph v20.03.0, indexing can be run in the background: https://dgraph.io/docs/query-language/#indexes-in-background

As of v20.03.1 in-progress indexing tasks can be tracked via /health (`"ongoing"` and `"indexing"`): https://dgraph.io/docs/deploy/#querying-health

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8882). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
