### ISSUE TITLE
[Ratel]: ACL issue - cannot assign group to user 

### ISSUE THREAD

**Issue by OmarAyo** [dgraph-io/ratel#216]
The issue is related to Ratel as I cannot assign groups to users. 

The only way to do this is via `dgraph acl mod ...`

Screenshots:

![Screenshot from 2020-06-15 12-35-05](https://user-images.githubusercontent.com/32968582/84648053-ac14dd80-af04-11ea-9160-17921e91b461.png)

Network console shows:
![Screenshot from 2020-06-15 12-37-12](https://user-images.githubusercontent.com/32968582/84648199-f4cc9680-af04-11ea-90a4-61ef549757a1.png)
]

@paulftw  FYI

**Comment by paulftw** [comment]
@OmarAyo thanks for the bug report. It should be an easy fix, but I’m traveling today.
Will definitely roll out a patch tomorrow if not earlier
