### ISSUE TITLE
Visualization no longer allows you to zoom out all the way

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#217]
We got this report from a user. This used to be possible? It's a big "WOW" feature when you can show a demo to users about the scale of the data by zooming out a lot.

**Comment by paulftw** [comment]
Works for me on play / latest in Chrome.
<img width="1352" alt="Screen Shot 2020-06-17 at 6 34 47 PM" src="https://user-images.githubusercontent.com/769142/84918502-56d5f900-b0c9-11ea-8d94-4b899862fc50.png">

We always had a hardcoded limit on how far you can zoom out, but that limit hasn't been touched for a year or more.

Can they provide more details on what query / graph is misbehaving?
At least a screenshot would help

**Comment by danielmai** [comment]
Hm, that's what I figured. I'll try to get more details.

**Comment by mikehawkes** [comment]
Sorry for the delay - I've cleared down and reinstalled today - and it looks like it's all doing what it should again. Sorry for any confusion - happy to close this one.

**Comment by paulftw** [comment]
no worries. good you've pinged us about a feature you cared about
