### ISSUE TITLE
Add a visual hint when a mutation passes or fails JSON.parse

### ISSUE THREAD

**Issue by paulftw** [dgraph-io/ratel#221]
See https://github.com/dgraph-io/ratel/issues/220

In that issue Ratel is doing (sort of) the right thing, but if there's a hard to spot error in JSON users are getting confused to why it's not interpreted as JSON.

Full solution involves:
1. UI to show (and force?) selection of JSON/RDF
2. Syntax highlight of where JSON parser is failing

Step 2 should be covered by other tasks.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8062). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
