### ISSUE TITLE
Predicate suggestion in console tab very slow with large schema

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/ratel#222]
With a schema of 250k predicates typing queries in the console tab is very cumbersome. Typing the first letter of a predicate, Ratel filters for matching predicates and provides a long long list of predicates. This takes like 30 seconds for the first letter and makes the browser stall. A predicates list of thousands of entries is of questionable value. The list of suggestions should be limited to the top 20 or 50. This improves performance and UX.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8063). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
