### ISSUE TITLE
Predicate suggestion has two entries for each predicate

### ISSUE THREAD

**Issue by EnricoMi** [dgraph-io/ratel#223]
The console tab has some predicate suggestion while I am typing my query. This is very useful to lookup long predicate names. However, it lists each predicate twice, once with `<` and `>` and once without:

![grafik](https://user-images.githubusercontent.com/44700269/86335594-0032f800-bc4f-11ea-8e87-d0aff70870de.png)

Predicates should only be listed *with* the angle brackets as this is good practice for predicates and helps to distinguish them from query language keywords. Alternatively, only predicates that contain "special" characters that requires angle brackets should be listed with brackets and not without.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8064). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
