### ISSUE TITLE
Add Poor-man’s auth to Ratel UI

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#224]
Reference: https://dgraph.io/docs/master/deploy/#dgraph-administration

Dgraph supports Poor-man’s auth. Which you can pass as an argument in the flag `--auth_token`.
For now, it protects Alter endpoint and some other admins operations, but in the future, it will protect mutations, queries, and GraphQl queries.

BTW, the flag mention "token" but you can literally use any Htpasswd Generator out there, also as it is just a string, you can pass any phrase or combination you want. I would strongly recommend a Htpasswd Generator or something safer like a "hash/Bcrypt".

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8065). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
