### ISSUE TITLE
Blatant Misuse of github issues logging

### ISSUE THREAD

**Issue by DarkBlaez** [dgraph-io/ratel#230]
Like many companies you are blatantly misusing github issues by closing issues and diverting off the site. Not sure why so many companies choose to do this other than guarding the pure number of open and outstanding issues which many such as mysef use to evaluate the progress of a project. Kindly stop this sort of gaming the system and stop diverting individuals off the site for issues posting.

DB

**Comment by manishrjain** [comment]
GitHub issues does not work for us. We have many public repositories and it is hard for us to keep track of issues across all these. Moreover, users tend to use GitHub issues as discussions. So, we have defragmented all GitHub issues over to Discourse, which is a great software designed for communities.

I'm not sure why you consider our decision to not use GitHub Issues as "blatant misuse" or "gaming the system." They both sound like emotionally charged statements.

All Ratel issues have been ported here: https://discuss.dgraph.io/c/issues/ratel/47

**Comment by DarkBlaez** [comment]
Actually they are not emotionally charged statements and the assertion is about as credible as mine. However, let me explain, many companies enjoy the use of GitHub, many enjoy the contributions by others to fix bugs and address their issues. However, a number of companies, let me name one to be precise, Joyent, tend to want the issues hidden behind a register-only forum. This allows them to hide the outstanding issues from potential customers. Having a bot automatically close issues is not acting in good-faith. Having users register to an additional site to post issues is also not what GitHub expects. Clearly choosing to use the repository feature of GitHub to store code but divert users away from the system to post issues is not acceptable for most. If you claim you are unable to manage the large number of issues across products, I wonder how much larger companies with a larger portfolio are able to do so actively.

Obviously it is your choice to do as you please, looking at the pure number of auto-closed issues indicates a number of problems and to amplify it, moving users to post on another system requiring registration to post issues reveals intent

DB
