### ISSUE TITLE
Support TLS client-cert authentication for Alphas configured with TLS cert.

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#31]
Some users running TLS-enabled clusters with client-auth want to still be able to connect to the cluster with Ratel.

Ratel currently supports server-auth, but not client-auth.

**Comment by paulftw** [comment]
implemented in master

**Comment by paulftw** [comment]
I thought this is for ACL. Reopening

**Comment by paulftw** [comment]
Ratel + TLS setup is documented here: https://docs.dgraph.io/deploy/#using-ratel-ui-with-client-authentication
