### ISSUE TITLE
How to install dgraph-ratel through binary mode in an arm environment

### ISSUE THREAD

**Issue by Zzt1993** [dgraph-io/ratel#311]
### What version of Ratel are you using?

latest

### What you did.

![image](https://github.com/dgraph-io/ratel/assets/95836616/4720b7b4-d286-4f16-a644-25c0f1f89808)

### What happened.

fatal: Needed a single revision

### Can we reproduce the issue?

[root@k3s-14 ratel@v0.0.0-20230409031452-074df688a0ff]# ./scripts/build.prod.sh
fatal: Needed a single revision

### Additional information

How to install dgraph-ratel through binary mode in an arm environment

**Comment by Zzt1993** [comment]
Thank you for your reply. I have already solved the problem, but I have encountered a new one

**Comment by Zzt1993** [comment]
Dgraph version   : v23.0.1

**Comment by Zzt1993** [comment]
Thank you for your reply. I have already solved the problem

**Comment by MichelDiz** [comment]
np,

Cheers.
