### ISSUE TITLE
Add more information about Schema and Filters.

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#34]
Before Ratel had information in the Frame Footer. It would be interesting to have a total of predicates and use pagination perhaps. Filters would also be interesting to return.

Update 2020: I gonna reformulate this.

By 2018 Schema's editor had few features, but they were extremely useful for large lists of predicates. For example. There was a search. Which filtered the predicates by name. And there was also pagination.

Pagination is great for giant schemas. For example, 21million RDF has over 250 predicates. Scrolling to locate a specific predicate is a bad experience.

There was also a box that we chose how many entries would be shown. 10, 20, 30 and etc.

At the bottom of the predicate, the list was information about how many entries were being displayed and which page we were on.

There were "previous" and "next" buttons.

It would be interesting to have a Filter by predicate type, an advanced search so to speak. For example, I want to see only `[uid]` type predicates that begin with B. Or 'See only predicates that are not part of some Type so I can fix it'. That way you can have better control of Schema.

Here is a pic of it

![Captura de Tela 2020-01-13 às 22 21 53](https://user-images.githubusercontent.com/6570955/72305939-2be80480-3654-11ea-8b2a-1f8f62249cb4.png)

![image](https://user-images.githubusercontent.com/6570955/80623704-fb6c8080-8a20-11ea-9fe7-b327c6ca9423.png)

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/0). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/8883). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
