### ISSUE TITLE
Dgraph-ratel crashes with a blank screen when click on an edge a Facet

### ISSUE THREAD

**Issue by henrymontagu** [dgraph-io/ratel#49]
When I am trying to click on edge that has a facet, the UI v1.0.10 crashes and turns to a white screen. I have attached a screen shot of the brower and the error printed by the console is below. Any help on solving this issue will be highly appreciated ?

```
TypeError: "i is undefined"
r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1267573
r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1267519
Rn https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:644941
n https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:658757
Zn https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:659138
yr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:665662
mr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:665042
dr https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:664071
or https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:663130
enqueueSetState https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:693462
setState https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:598934
handleNodeSelected https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1221780
configNetwork https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:1264397
r https://d1ocqy7wcgv7nr.cloudfront.net/static/js/main.js:1:708791
```

![screen shot 2018-12-27 at 10 32 36 am](https://user-images.githubusercontent.com/34367742/50470201-08123c00-09c9-11e9-95a7-2c4a8fc9643b.png)

**Comment by henrymontagu** [comment]
Hi,

The issue can be replicated if you connect to https://play.dgraph.io/ on the ratel UI and try to run the query below which loads the data referring to facets example in this page https://docs.dgraph.io/mutations/#facets. 

{
  node(func: uid(0x1)) {
    uid
    expand(_all_) {
      uid
      expand(_all_)
    }
  }
}

Try to click on any of the edges that have facets and it blanks and this error occurs.

**Comment by MichelDiz** [comment]
hummm, I've just tested this and is reproducible
But is not happening in dev https://play.dgraph.io/?dev

```
{
  data(func: eq(name, "Alice")) {
     expand(_all_){expand(_all_) }
  }
}
```

**Comment by henrymontagu** [comment]
Hi Michel,

I have tried to use the ratel in the ?dev. However, when you click on any of the edges that have facets, they don’t show any of the facets that otherwise appear in the ?latest. I am looking adding properties to the edges and make them visible in the UI. Is there any other way to do this other than adding facets to the edges?
