### ISSUE TITLE
Use Ratel with server that has TLS client auth "REQUIREANDVERIFY"

### ISSUE THREAD

**Issue by emhagman** [dgraph-io/ratel#51]
Does anyone know how I can add my "client" certificate on Chrome for example when using the Ratel web interface. If I only use SSL (not client auth required) for the Dgraph servers, I can accept a untrusted source in Chrome but if I require a valid client cert / key,  I am not sure how I can make queries through Chrome.

Version: dgraph:dev (nightly?)
Memory: 64GB
OS: Docker on Ubuntu 16.04

**Comment by d4l3k** [comment]
Any update on this? This makes ratel pretty much useless in a production environment :/

**Comment by paulftw** [comment]
Documented here: https://docs.dgraph.io/deploy/#using-ratel-ui-with-client-authentication
