### ISSUE TITLE
dgraph-ratel wait time not long enough

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/ratel#54]
Copied from https://github.com/dgraph-io/dgraph/issues/2408

"Whenever I run a slightly time-consuming query, the dgraph-ratel fails to render the result due to timeout.
Other clients could wait for as long as it needs for the result to arrive.
Can you give an option to set wait timeout in dgraph-ratel UI?"

**Comment by paulftw** [comment]
Ratel itself doesn't have a query timeout.
Only case I can think of is nginx timeouts on play.dgraph.io, and those only affect queries of the play database.

Are you running dgraph & ratel locally?

(closing issue until more information is available)
