### ISSUE TITLE
Mutation running twice

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#56]
When we make a mutation. In the Console panel and then we go to "Schema or Explore" or another. 
And then we go back to the Console. Ratel performs a new mutation. Duplicating the data.

**Comment by paulftw** [comment]
I believe this got fixed with the history / panels redesign. Queries would run twice in the old layout but not in the new.

@MichelDiz can you please check whether this is still happening with the mutations you have?

**Comment by MichelDiz** [comment]
I've Just tested on https://play.dgraph.io/ and seems to be solved.

Thanks Paul!

**Comment by paulftw** [comment]
Fixed. Writing an e2e test to make sure this issue doesn't resurface again
