### ISSUE TITLE
Add JSON config file for Ratel

### ISSUE THREAD

**Issue by tr37ion** [dgraph-io/ratel#57]
Please add a `--config=/path/file.json` option to ratel  for more consistancy. Consider renaming `-addr` to something more descriptive eg. `--host`. Mind the `--`, please.

Btw. is `telemetry` missing in `--help` option or no more valid?

**Comment by paulftw** [comment]
Here's the flags that Ratel currently recognizes:
`
	portPtr := flag.Int("port", defaultPort, "Port on which the ratel server will run.")
	addrPtr := flag.String("addr", defaultAddr, "Address of the Dgraph server.")
	versionFlagPtr := flag.Bool("version", false, "Prints the version of ratel.")
`

IIRC `--my` is used to tell alphas and zeros what is their own network host/port. In Ratel `addr` is the name of the server it'd connect to.

JSON config sounds like a cool feature

**Comment by danielmai** [comment]
With #182 merged, you should be able to use config files in JSON, TOML, YAML, HCL, envfile orJava properties config files with the integration of Viper/Cobra.

**Comment by minhaj-shakeel** [comment]
**Github issues have been deprecated.** 
This issue has been moved to [discuss](https://discuss.dgraph.io/t/7964). You can follow the conversation there and also subscribe to updates by changing your notification preferences.

 <img src="https://github.com/dgraph-io/benchmarks/blob/master/images/SetNotifications.png?raw=true" alt="drawing" width="40%"/>
