### ISSUE TITLE
Facets are not displayed anymore when mouse is hover an edge

### ISSUE THREAD

**Issue by Issif** [dgraph-io/ratel#63]
Hi,

Since migration to D3js for ratel, facets are not displayed anymore when the mouse is over an edge.

Here the result I got previously :

![image](https://user-images.githubusercontent.com/4520100/52590500-bbcc6f80-2e41-11e9-8b2e-fbe6fcc00961.png)

I'm currently using, Commit: a23ea13, notified as latest stable release.

Regards,

**Comment by paulftw** [comment]
Yes, facets are yet to be implemented in the new ratel graph. Didn't know if many people were actually using them, but seems like quite a few do. Will prioritize it accordingly

**Comment by Issif** [comment]
Hi,

Any update for this issue? Thanks.

**Comment by paulftw** [comment]
Added support for facets in 0392fdb0561414c74e918db8dda5f9cf36e812b3
