### ISSUE TITLE
Cannot copy partial JSON response

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#64]
I tried copying from the JSON response pane but there's no option to copy.

![2019-02-13-091345_3440x1440_scrot](https://user-images.githubusercontent.com/2251820/52730306-e7e60e80-2f6f-11e9-83d6-3d392b106ef8.png)

It seems like selection for copying/pasting is only possible in the query/mutation pane.

**Comment by paulftw** [comment]
There's a button to copy whole response in the top right of the results pane.

Right now the query editor is hijacking the keyboard shortcuts.
Will see if there's a fix for that.

**Comment by danielmai** [comment]
In Ratel the response cannot be searched via a browser's "Find..." functionality. That issue seems related to this one.

**Comment by paulftw** [comment]
Fixed in https://github.com/dgraph-io/ratel/commit/fc9f833aaacca7ab4b9f67558110dc12dc5ef65d
