### ISSUE TITLE
Support inputting arguments for GraphQL Variables

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#65]
In Ratel, the only way to run queries with [GraphQL Variables](https://docs.dgraph.io/query-language#graphql-variables) is to pass the arguments as default values (e.g., `$a: int = 10`). It'd be useful to input arguments to a query without modifying the query itself.

**Comment by felixfbecker** [comment]
Yes, this makes it really difficult to copy-paste queries (need to manually replace all the variables with values)

**Comment by paulftw** [comment]
Query Variables UI is available in the dev builds. Please post feedback here

**Comment by paulftw** [comment]
Fixed in https://github.com/dgraph-io/ratel/pull/210
