### ISSUE TITLE
Ratel runs historic queries in the background

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#70]
I had a bunch of expensive queries in my history list. When I load Ratel they are run again, which isn't what I expected. I expect queries only to be run when I tell them to. Otherwise, they should wait their turn.

**Comment by paulftw** [comment]
Closing as #86 is the same problem but with a bit more discussion

**Comment by danielmai** [comment]
#86 was about running multiple queries executing after clicking Run. This issue is about the query running at page-startup without clicking Run at all.

Ratel should not be running queries automatically without clicking the Run button. This can significantly slow down both Ratel and Dgraph unintentionally, and there's no way to cancel an ongoing query from Ratel.
