### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/ratel#75]
The DGraph GUI (latest) has an issue when you resize the pane in between the LHS (query enterer) and RHS visual portion.

Once you resize it, the text box on the LHS loses track of the cursor until you press a key.

**Comment by paulftw** [comment]
The focus behavior is annoying and now that you've shown it I cannot unsee it.
But it's not different to editor losing focus when a button or JSON tab is clicked.
A fix isn't impossible but won't be clean - remember if editor is focused when drag starts, store that value somewhere, focus back when drag finishes.
It's a wontfix issue until after the redesign.

Explorer is overall very experimental, so also a wontfix for now.
