### ISSUE TITLE
ratel: visually delete nodes

### ISSUE THREAD

**Issue by pjebs** [dgraph-io/ratel#76]
It would be great if we can delete a node in ratel by clicking on a button.
It is inconvenient to delete using code sometimes. Sometimes during development it's just easier for me to drop the db and start afresh. 

An improvement would be to do various common actions visually and see the query generated via some log in ratel as a FYI.

**Comment by paulftw** [comment]
We've merged in a feature that generates "drop node" query. Interactive dropping the node will be added as a part of a bigger interactive editing feature
