### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by j0hnsmith** [dgraph-io/ratel#79]
New to dgraph, I have lots of docs tabs open and a ratel tab, because all the favicons are the same I can't tell which is tab is the ratel one. 

Can you change the design of the ratel favicon, doesn't have to be a big change, even just change the colour slightly?

**Comment by paulftw** [comment]
Ratel already has a different icon. Make sure you are using one of the last releases, or the play.dgraph.io version


<img width="720" alt="Screen Shot 2019-04-26 at 11 34 21 AM" src="https://user-images.githubusercontent.com/769142/56794705-5f110c00-6817-11e9-80c7-ac2d7b2eb4eb.png">

**Comment by j0hnsmith** [comment]
Indeed it does :+1:
