### ISSUE TITLE
Unable to connect to dgraph server

### ISSUE THREAD

**Issue by jueyoq** [dgraph-io/ratel#84]
The default port number of the DGraph component used, but one cannot connect and the database works fine.

**Comment by jueyoq** [comment]
It is indeed port 8080

**Comment by paulftw** [comment]
It does default to port 8080 on a clean installation.
Can you please try with an incognito window?
What flags do you pass when running dgraph and ratel?

I'm closing this issue as non-reproducible for now. Will revisit once I get more information
