### ISSUE TITLE
Ratel on Windows PC (# of queries bug)

### ISSUE THREAD

**Issue by lolcoolkat** [dgraph-io/ratel#86]
If you suspect this could be a bug, follow the template.

- What version of Dgraph are you using?
**v1.0.14**

- Have you tried reproducing the issue with latest release?
**Yes (Not with v1.0.15 though)**

- What is the hardware spec (RAM, OS)?
**24GB of RAM and Windows 10**

- Steps to reproduce the issue (command/config used to run Dgraph).
1) Download the binaries you need for Windows
2) Run `dgraph zero` in 1 cmd window.
2) Run `dgraph alpha --lru_mb 2048 --zero localhost:5080` in a 2nd cmd window.
3) Run `dgraph-ratel` in a 3rd cmd window.
4) Go to http://localhost:8000 and add a dgraph schema + add data.
5) Run any query (it should run perfect, and `ts.start_ts` should go up by 1 every time)
6) Ctrl-C ratel running in the 3rd cmd.
7) Run `dgraph-ratel` again in the same cmd.
8) Run the query again.. and **you should see the `start_ts` going up by more than 1**. (There are multiple queries starting now.. idk why)

- Expected behaviour and actual result.
**`start_ts` should only go up by 1 every time you run a query. It's going up by 3 or 4 now for me each time I run a query in my local ratel instance.**

**Comment by lolcoolkat** [comment]
Can confirm this is also an issue on Linux too. Now it's running 6 queries every single time I click run :/

**Comment by lolcoolkat** [comment]
You can also go to https://play.dgraph.io/?latest 
Everytime you run a query the `start_ts` goes up by 3 :P

**Comment by danielmai** [comment]
I see this issue as well. It's not good that Ratel runs the same query multiple times after clicking th e Run button once.

**Comment by lolcoolkat** [comment]
Hope this can be fixed soon :( It's hard to debug stuff with tons of queries being fired at the same time.

**Comment by lolcoolkat** [comment]
Any updates to this?? :) @paulftw @danielmai

**Comment by danielmai** [comment]
We're working on some code refactoring that would ultimately lead to this issue getting fixed. @paulftw is working on it.

**Comment by lolcoolkat** [comment]
Thanks for the update @danielmai :)

**Comment by paulftw** [comment]
Fixed in master and live in the `?dev` version

**Comment by lolcoolkat** [comment]
@paulftw any ideas to when this will be merged into master?
