### ISSUE TITLE
Update Ratel to use new HTTP API

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#87]
Ref: https://github.com/dgraph-io/tutorial/issues/66

More details here https://github.com/dgraph-io/dgraph/pull/3365

![Captura de Tela 2019-05-24 às 13 02 36](https://user-images.githubusercontent.com/6570955/58341132-e1471d00-7e23-11e9-991a-0ddf0418de26.png)

**Comment by paulftw** [comment]
Fixed in master
