### ISSUE TITLE
Data Explorer is slow

### ISSUE THREAD

**Issue by KevOrr** [dgraph-io/ratel#89]
Currently, the Data Explorer tab will count predicates in batches of 4, every 2 seconds. This causes a significant delay for graphs with many predicates, since a large portion of time can be spent waiting for the 2 second timer to expire.

https://github.com/dgraph-io/ratel/blob/43115275eeff79b593dafada22916dc17fe92045/client/src/components/DataExplorer/index.js#L116-L128

**Comment by Aelbannan** [comment]
Fixed in #148
