### ISSUE TITLE
Update local development instructions.

### ISSUE THREAD

**Issue by martinmr** [dgraph-io/ratel#90]
Build instructions are not accurate.

**Comment by paulftw** [comment]
Can you please be more specific?
readme doesn't actually have any build instructions, let alone inaccurate

**Comment by martinmr** [comment]
It's on INSTRUCTIONS.md, sorry. The local development section is inaccurate since the build.local.sh script does not exist.

**Comment by paulftw** [comment]
67cc8999019908adf3f816f5b3e73d606f7013cc

Animesh told me he could build ratel following current instructions
