### ISSUE TITLE
URL error/Bug

### ISSUE THREAD

**Issue by MichelDiz** [dgraph-io/ratel#94]
One Error has been happening to me constantly. On Windows and MacOS Mojave. Sometimes I need to change the Dgraph address in Ratel this happens (See image). And the only way to recover is by going to the browser tools in "Application, Clear Storage, and finally Clear Site Data". That way I can apply any address again.

This seems to be related to "health" endpoint.

Addr used:
`http://localhost:8080/`

![Captura de Tela (18)](https://user-images.githubusercontent.com/6570955/62228536-378c8b00-b394-11e9-9264-ef037d6f25fd.png)

**Comment by danielmai** [comment]
I see when I click "Update" button after updating the address.

However, if I press Enter while in the server URL text field, it connects fine.

**Comment by paulftw** [comment]
Fixed in https://github.com/dgraph-io/ratel/commit/89d3a0cd5c3fb0fc1196eb93b745a2a7828e8b42

Please re-open if the problem persists
