### ISSUE TITLE
Clicking the trash can icon 🗑from the response pane results in blank page

### ISSUE THREAD

**Issue by danielmai** [dgraph-io/ratel#95]
Steps to reproduce:

1. Send a number of queries/mutations
2. On the top-right corner, click on the trash can icon to close the results pane for each of the historical requests.
3. End up with a blank page with an error in the console.

**Comment by paulftw** [comment]
Cannot reproduce. Do you still see this? Is it on play or local ratel?
Can you please upload a screenshot or copypaste the error frim console?

**Comment by danielmai** [comment]
I can't reproduce it now either. I tried ?latest and ?local.

**Comment by campoy** [comment]
This is the error message I saw last time:
![Screen Shot 2019-07-29 at 10 41 45 AM](https://user-images.githubusercontent.com/2237452/62496724-adc33000-b78e-11e9-891d-3b3fbf5c8f17.png)

Also, I'm able to reproduce it still.

**Comment by campoy** [comment]
After cleaning the local storage for the website the error disappeared, so this should be something that has changed very recently for `latest`.

**Comment by campoy** [comment]
This is *still* happening on "latest", what is your plan to fix this @paulftw ?

**Comment by paulftw** [comment]
Should be fixed now
